---
kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/leonenkoa/nginx-prometheus

steps:
- name: test
  image: docker.affisecorp.com/library/gobuilder:1.12.1
  commands:
  - go test ./...
  environment:
    GO111MODULE: on
  when:
    branch:
    - master
    - feature/*

- name: build
  image: docker.affisecorp.com/library/gobuilder:1.12.1
  commands:
  - go get github.com/blind-oracle/nginx-prometheus
  - cd $GOPATH/src/github.com/blind-oracle/nginx-prometheus
  - dep ensure
  - GOOS=linux GOARCH=amd64 go build -o nginx-prometheus-linux-amd64
  when:
    event:
    - tag
    - push
    branch:
    - master
    - feature/*

- name: build_master_image
  image: plugins/docker
  settings:
    registry: docker.affisecorp.com
    repo: docker.affisecorp.com/library/nginx-prometheus
    auto_tag: false
    purge: true
    insecure: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    branch:
    - master

- name: build_release_image
  image: plugins/docker
  settings:
    registry: docker.affisecorp.com
    repo: docker.affisecorp.com/library/nginx-prometheus
    auto_tag: true
    purge: true
    insecure: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - tag
    branch:
    - master
    - feature/*

- name: slack
  image: plugins/slack
  settings:
    channel: ci
    webhook: https://hooks.slack.com/services/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
    image_url: https://picsum.photos/id/406/256/256
  when:
    status:
    - success
    - failure

image_pull_secrets:
  - dockerconfigjson