---
kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/leonenkoa/nginx-prometheus

steps:
- name: test
  image: docker.affisecorp.com/library/gobuilder:1.12.1
  commands:
  - make lint-all
  environment:
    GO111MODULE: on
  when:
    branch:
    - master
    - feature/*

- name: build
  image: docker.affisecorp.com/library/gobuilder:1.12.1
  commands:
  - make linux
  when:
    event:
    - tag
    - push
    branch:
    - master
    - feature/*

- name: build_postback_master_image
  image: docker
  settings:
    docker_username:
      from_secret: docker_username
    docker_password:
      from_secret: docker_password
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.affisecorp.com
  - "docker build --rm -f Dockerfile -t docker.affisecorp.com/library/nginx-prometheus:latest ."
  - "docker push docker.affisecorp.com/library/nginx-prometheus:latest"
  - "docker rmi docker.affisecorp.com/library/nginx-prometheus:latest"
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    branch:
    - master
    - feature/*

- name: build_postback_image
  image: docker
  settings:
    docker_username:
      from_secret: docker_username
    docker_password:
      from_secret: docker_password
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.affisecorp.com
  - "docker build --rm -f Dockerfile -t docker.affisecorp.com/library/nginx-prometheus:${DRONE_TAG##v} ."
  - "docker push docker.affisecorp.com/library/nginx-prometheus:${DRONE_TAG##v}"
  - "docker rmi docker.affisecorp.com/library/nginx-prometheus:${DRONE_TAG##v}"
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - tag
    branch:
    - master
    - feature/*

- name: slack
  image: plugins/slack
  settings:
    room: ci
    webhook: https://hooks.slack.com/services/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
    when:
      status:
      - success
      - failure

volumes:
- name: docker
  host:
    path: /var/run/docker.sock